### ISSUE TITLE
How to close the SFTP session?

### ISSUE THREAD

**Issue by netthier** [AspectUnk/russh-sftp#12]
When using russh-sftp with a Windows remote, I observe that `sftp-server.exe` processes are seemingly "leaking" until my program exits.
This is probably due to me dynamically creating new sftp clients and then simply dropping them, which apparently is not sufficient to close the connection.
As `client::SftpSession::new()` consumes the channel stream however, I'm not sure how to close it.
I see a `close()` method in `RawSftpSession`, but would prefer being able to use the high-level abstraction.

<details>
<summary>Task Manager</summary>
<img src="https://github.com/AspectUnk/russh-sftp/assets/66856670/fdf958d1-dbe0-4405-aa0b-095f934f5fc2">
</details>

**Comment by AspectUnk** [comment]
Method `close()` in RawSftpSession closes the handle, not the session. I opened a PR #13  which should fix this. Please reproduce this again and give feedback

**Comment by netthier** [comment]
I can confirm that the linked PR fixes the issue with both my reproducer as well as my actual application.
Thank you for the very quick fix!

**Comment by AspectUnk** [comment]
All fixed published in `2.0.0-beta.4`. Thank you, I didn’t think I’d miss such a basic thing.
