### ISSUE TITLE
How to change working directory

### ISSUE THREAD

**Issue by Andycharalambous** [AspectUnk/russh-sftp#25]
Stupid question but how do you change the working directory? I can see every other possible operation in SftpSession except for one that can issue the equivalent of "cd <folder>".

**Comment by AspectUnk** [comment]
Hello. In the context of a library, a separate implementation of the "cd" command is not necessary, as it typically does two things: first, it sends a request for [path canonicalization](https://docs.rs/russh-sftp/2.0.0-beta.4/russh_sftp/client/struct.SftpSession.html#method.canonicalize), and then it sends a request to [retrieve metadata](https://docs.rs/russh-sftp/2.0.0-beta.4/russh_sftp/client/struct.SftpSession.html#method.metadata).
