### ISSUE TITLE
Server: Directories are appearing as files in filezilla

### ISSUE THREAD

**Issue by MarkusTieger** [AspectUnk/russh-sftp#52]
Directories are appearing as files in filezilla (not tested with other sftp software).

Steps to reproduce:
- Run the example server (which has two directories: "foo", "bar". FileAttributes::default() is used, which defaults to directories).
- Connect to the server using filezilla
- "foo" and "bar" are appearing as files

**Comment by AspectUnk** [comment]
Usually SFTP clients check attributes, but FileZilla for some unknown reason uses longname for this, which in example was not filled in due to lack of need. Anyway, fixed. Thank you!
